# Generated by Django 3.2 on 2022-04-20 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_crm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
