# Generated by Django 3.2 on 2022-04-27 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('accounts', '0001_initial'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact'),
        ),
        migrations.AddField(
            model_name='message',
            name='dialog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.dialog_chat'),
        ),
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.group_chat'),
        ),
        migrations.AddField(
            model_name='group_chat',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='my_admin_groups', to='accounts.Employe'),
        ),
        migrations.AddField(
            model_name='group_chat',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_groups', to='accounts.employe'),
        ),
        migrations.AddField(
            model_name='group_chat',
            name='members',
            field=models.ManyToManyField(related_name='my_follow_groups', to='accounts.Employe'),
        ),
        migrations.AddField(
            model_name='dialog_chat',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialog_in_receiver', to='accounts.employe'),
        ),
        migrations.AddField(
            model_name='dialog_chat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_in_sender', to='accounts.employe'),
        ),
    ]
