# Generated by Django 3.2 on 2022-04-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_profile',
            field=models.BooleanField(default=False),
        ),
    ]
