# Generated by Django 3.2 on 2022-04-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_has_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postion',
            name='position',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
