# Generated by Django 3.2 on 2022-04-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220414_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(choices=[('', ''), ('CEO', 'CEO'), ('Agent', 'Agent'), ('Manager-dispatcher', 'Manager-dispatcher'), ('Accountant', 'Accountant'), ('Sales Manager', 'Sales Manager'), ('Office Manager', 'Office Manager')], default=False, max_length=250, null=True),
        ),
    ]
