# Generated by Django 3.2 on 2022-05-07 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_postion_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='employe',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_section', to='accounts.section'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='employe',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postion',
            name='position',
            field=models.CharField(choices=[('', ''), ('director', 'director'), ('deputy', 'deputy'), ('worker', 'worker')], default=False, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(),
        ),
    ]
