# Generated by Django 3.2 on 2022-05-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220508_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='country',
            field=models.CharField(blank=True, choices=[('Tashkent', 'Tashkent'), ('Samarkand', 'Samarkand'), ('Andijan', 'Andijan'), ('Karakalpakstan', 'Karakalpakstan'), ('Ferghana', 'Ferghana'), ('Bukhoro', 'Bukhoro'), ('Namangan', 'Namangan'), ('Khorezm', 'Khorezm'), ('Kashkadarya', 'Kashkadarya'), ('Jizzakh', 'Jizzakh'), ('Surkhandaryo', 'Surkhandaryo'), ('Navoi', 'Navoi'), ('Sirdaryo', 'Sirdaryo')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='remember_me',
            field=models.BooleanField(default=False),
        ),
    ]
