# Generated by Django 3.2 on 2022-05-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220512_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='country',
            field=models.CharField(blank=True, choices=[('Tashkent', 'Tashkent'), ('Samarkand', 'Samarkand'), ('Andijan', 'Andijan'), ('Nukus', 'Nukus'), ('Ferghana', 'Ferghana'), ('Bukhara', 'Bukhara'), ('Namangan', 'Namangan'), ('Urganch', 'Urganch'), ('Qarshi', 'Qarshi'), ('Jizzakh', 'Jizzakh'), ('Termiz', 'Termiz'), ('Navoiy', 'Navoiy'), ('Sirdaryo', 'Sirdaryo')], max_length=120, null=True),
        ),
    ]
