# Generated by Django 3.2 on 2022-05-24 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220516_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employe'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='gender',
            field=models.CharField(blank=True, choices=[('', ''), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_position', to='accounts.postion'),
        ),
    ]
