# Generated by Django 3.2 on 2022-05-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220524_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='email_add',
        ),
        migrations.AddField(
            model_name='employe',
            name='password_email',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
