# Generated by Django 3.2 on 2022-05-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_employe_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='password_email',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
