# Generated by Django 3.2 on 2022-05-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_employe_password_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employe',
            name='password_email',
            field=models.CharField(max_length=35),
        ),
    ]
