# Generated by Django 3.2 on 2022-05-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220524_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='password_email',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
