# Generated by Django 3.2 on 2022-05-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220524_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employe',
            name='gender',
            field=models.CharField(blank=True, choices=[('Not specified', 'Not specified'), ('Male', 'Male'), ('Female', 'Female')], default='Not specified', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='password_email',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
